apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : cms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: control
  source:
    path   : "helm/platform-common-services/control-plane/cms"
    repoURL: "https://github.com/zbykovskyi/argocd.git"
    targetRevision: multienv
    helm:
      valueFiles:
        - /environments/dev/control-plane/applications/values/cms-values.yaml

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
